name: grohealth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_database: ^10.3.5
  firebase_storage: ^11.7.5
  lottie: ^2.7.0
  get: ^4.6.6
  flutter_mdi_icons: ^0.1.1
  material_design_icons_flutter: ^7.0.7296
  android_alarm_manager_plus: ^4.0.1
#  flutter_local_notifications: ^17.0.0
  alarm: ^3.0.14
  permission_handler: ^11.3.1
  image_picker: ^1.1.1
  google_generative_ai: ^0.4.0
  intl: ^0.19.0
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/
